spring:
  data:
    mongodb:
      uri: mongodb+srv://akritgupta00:123321@projects.kojl9pn.mongodb.net/?retryWrites=true&w=majority&appName=projects
      database: projects
  mail:
    host: smtp.gmail.com
    port: 587
    username: akritttgupta@gmail.com
    password: meld vcmg iwar ofkf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
gemini:
  api:
    key: AIzaSyDwwgyCekyc_mUO9jZQlgc95xEN3Tusblc

portfolio:
  owner:
    email: akritttgupta@gmail.com

server:
  port: 8080

