spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: projects
  mail:
    host: smtp.gmail.com
    port: 587
    username: akritttgupta@gmail.com
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
gemini:
  api:
    key: ${GEMINI_API_KEY}

portfolio:
  owner:
    email: akritttgupta@gmail.com



